name: AutomatedTests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Test Case 1
        run: |
          python find_lowest_number.py test_data/test1_input.txt output.txt
          diff -u output.txt test_data/test1_expected.txt

      - name: Run Test Case 2
        run: |
          python find_lowest_number.py test_data/test2_input.txt output.txt
          diff -u output.txt test_data/test2_expected.txt

      - name: Run Test Case 3
        run: |
          python find_lowest_number.py test_data/test3_input.txt output.txt
          diff -u output.txt test_data/test3_expected.txt
